# Generated by Django 5.1.5 on 2025-01-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='15-01-2004'),
        ),
    ]
